services:
  python:
    container_name: bingeable-py
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/var/bingeable
      - /var/bingeable/__pypackages__ # https://stackoverflow.com/a/32785014
